/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public  class MInsertMacroPart extends Macro{
    
    String field_ReferencedMacroName;
    
    final List<Macro> list_EnclosingClassName;
    
    final Context EnclosingClassNameContext = new Context();
    
    final InternalValue EnclosingClassNameValue;
    
    private DSeparator EnclosingClassNameSeparator;
    
    private DBeforeFirst EnclosingClassNameBeforeFirst;
    
    private DAfterLast EnclosingClassNameAfterLast;
    
    private DNone EnclosingClassNameNone;
    
    String field_IndexBuilder;
    
    String field_IndexInsert;
    
    final List<Macro> list_MacroBodyParts;
    
    final Context MacroBodyPartsContext = new Context();
    
    final InternalValue MacroBodyPartsValue;
    
    private DSeparator MacroBodyPartsSeparator;
    
    private DBeforeFirst MacroBodyPartsBeforeFirst;
    
    private DAfterLast MacroBodyPartsAfterLast;
    
    private DNone MacroBodyPartsNone;
    
    final List<Macro> list_SetInternals;
    
    final Context SetInternalsContext = new Context();
    
    final InternalValue SetInternalsValue;
    
    private DSeparator SetInternalsSeparator;
    
    private DBeforeFirst SetInternalsBeforeFirst;
    
    private DAfterLast SetInternalsAfterLast;
    
    private DNone SetInternalsNone;
    
    final List<Macro> list_SingleElementLists;
    
    final Context SingleElementListsContext = new Context();
    
    final InternalValue SingleElementListsValue;
    
    private DSeparator SingleElementListsSeparator;
    
    private DBeforeFirst SingleElementListsBeforeFirst;
    
    private DAfterLast SingleElementListsAfterLast;
    
    private DNone SingleElementListsNone;
    
    MInsertMacroPart(String pReferencedMacroName, String pIndexBuilder, String pIndexInsert, Macros macros){
        
        
        this.setMacros(macros);
        this.setPReferencedMacroName(pReferencedMacroName);
        this.list_EnclosingClassName = new LinkedList<>();
        this.setPIndexBuilder(pIndexBuilder);
        this.setPIndexInsert(pIndexInsert);
        this.list_MacroBodyParts = new LinkedList<>();
        this.list_SetInternals = new LinkedList<>();
        this.list_SingleElementLists = new LinkedList<>();
        
        this.EnclosingClassNameValue = new InternalValue(this.list_EnclosingClassName, this.EnclosingClassNameContext);
        this.MacroBodyPartsValue = new InternalValue(this.list_MacroBodyParts, this.MacroBodyPartsContext);
        this.SetInternalsValue = new InternalValue(this.list_SetInternals, this.SetInternalsContext);
        this.SingleElementListsValue = new InternalValue(this.list_SingleElementLists, this.SingleElementListsContext);
    }
    
    private void setPReferencedMacroName( String pReferencedMacroName ){
        if(pReferencedMacroName == null){
            throw ObjectMacroException.parameterNull("ReferencedMacroName");
        }
    
        this.field_ReferencedMacroName = pReferencedMacroName;
    }
    
    public void addAllEnclosingClassName(
                    List<Macro> macros){
    
        if(macros == null){
            throw ObjectMacroException.parameterNull("EnclosingClassName");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        int i = 0;
        
        for(Macro macro : macros) {
            if(macro == null) {
                throw ObjectMacroException.macroNull(i, "EnclosingClassName");
            }
        
            if(this.getMacros() != macro.getMacros()){
                throw ObjectMacroException.diffMacros();
            }
        
            this.verifyTypeEnclosingClassName(macro);
            this.list_EnclosingClassName.add(macro);
            this.children.add(macro);
            Macro.cycleDetector.detectCycle(this, macro);
        
            i++;
        }
    }
    
    
    void verifyTypeEnclosingClassName (Macro macro) {
        macro.apply(new InternalsInitializer("EnclosingClassName"){
            @Override
            void setPlainText(MPlainText mPlainText){
            
                
                
            }
        });
    }
    
    public void addEnclosingClassName(MPlainText macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("EnclosingClassName");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_EnclosingClassName.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    private void setPIndexBuilder( String pIndexBuilder ){
        if(pIndexBuilder == null){
            throw ObjectMacroException.parameterNull("IndexBuilder");
        }
    
        this.field_IndexBuilder = pIndexBuilder;
    }
    
    private void setPIndexInsert( String pIndexInsert ){
        if(pIndexInsert == null){
            throw ObjectMacroException.parameterNull("IndexInsert");
        }
    
        this.field_IndexInsert = pIndexInsert;
    }
    
    public void addAllMacroBodyParts(
                    List<Macro> macros){
    
        if(macros == null){
            throw ObjectMacroException.parameterNull("MacroBodyParts");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        int i = 0;
        
        for(Macro macro : macros) {
            if(macro == null) {
                throw ObjectMacroException.macroNull(i, "MacroBodyParts");
            }
        
            if(this.getMacros() != macro.getMacros()){
                throw ObjectMacroException.diffMacros();
            }
        
            this.verifyTypeMacroBodyParts(macro);
            this.list_MacroBodyParts.add(macro);
            this.children.add(macro);
            Macro.cycleDetector.detectCycle(this, macro);
        
            i++;
        }
    }
    
    
    void verifyTypeMacroBodyParts (Macro macro) {
        macro.apply(new InternalsInitializer("MacroBodyParts"){
            @Override
            void setInitStringBuilder(MInitStringBuilder mInitStringBuilder){
            
                
                
            }
            
            @Override
            void setStringPart(MStringPart mStringPart){
            
                
                
            }
            
            @Override
            void setParamInsertPart(MParamInsertPart mParamInsertPart){
            
                
                
            }
            
            @Override
            void setEolPart(MEolPart mEolPart){
            
                
                
            }
            
            @Override
            void setInsertMacroPart(MInsertMacroPart mInsertMacroPart){
            
                
                
            }
        });
    }
    
    public void addMacroBodyParts(MInitStringBuilder macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("MacroBodyParts");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_MacroBodyParts.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addMacroBodyParts(MStringPart macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("MacroBodyParts");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_MacroBodyParts.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addMacroBodyParts(MParamInsertPart macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("MacroBodyParts");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_MacroBodyParts.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addMacroBodyParts(MEolPart macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("MacroBodyParts");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_MacroBodyParts.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addMacroBodyParts(MInsertMacroPart macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("MacroBodyParts");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_MacroBodyParts.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addAllSetInternals(
                    List<Macro> macros){
    
        if(macros == null){
            throw ObjectMacroException.parameterNull("SetInternals");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        int i = 0;
        
        for(Macro macro : macros) {
            if(macro == null) {
                throw ObjectMacroException.macroNull(i, "SetInternals");
            }
        
            if(this.getMacros() != macro.getMacros()){
                throw ObjectMacroException.diffMacros();
            }
        
            this.verifyTypeSetInternals(macro);
            this.list_SetInternals.add(macro);
            this.children.add(macro);
            Macro.cycleDetector.detectCycle(this, macro);
        
            i++;
        }
    }
    
    
    void verifyTypeSetInternals (Macro macro) {
        macro.apply(new InternalsInitializer("SetInternals"){
            @Override
            void setSetInternal(MSetInternal mSetInternal){
            
                
                
            }
        });
    }
    
    public void addSetInternals(MSetInternal macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("SetInternals");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_SetInternals.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addAllSingleElementLists(
                    List<Macro> macros){
    
        if(macros == null){
            throw ObjectMacroException.parameterNull("SingleElementLists");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        int i = 0;
        
        for(Macro macro : macros) {
            if(macro == null) {
                throw ObjectMacroException.macroNull(i, "SingleElementLists");
            }
        
            if(this.getMacros() != macro.getMacros()){
                throw ObjectMacroException.diffMacros();
            }
        
            this.verifyTypeSingleElementLists(macro);
            this.list_SingleElementLists.add(macro);
            this.children.add(macro);
            Macro.cycleDetector.detectCycle(this, macro);
        
            i++;
        }
    }
    
    
    void verifyTypeSingleElementLists (Macro macro) {
        macro.apply(new InternalsInitializer("SingleElementLists"){
            @Override
            void setNewStringValue(MNewStringValue mNewStringValue){
            
                
                
            }
        });
    }
    
    public void addSingleElementLists(MNewStringValue macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("SingleElementLists");
        }
        if(this.cacheBuilder != null){
            throw ObjectMacroException.cannotModify("InsertMacroPart");
        }
        
        if(this.getMacros() != macro.getMacros()){
            throw ObjectMacroException.diffMacros();
        }
    
        this.list_SingleElementLists.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    String buildReferencedMacroName(){
    
        return this.field_ReferencedMacroName;
    }
    
    private String buildEnclosingClassName(){
        StringBuilder sb = new StringBuilder();
        Context local_context = EnclosingClassNameContext;
        List<Macro> macros = this.list_EnclosingClassName;
    
        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;
    
        if(this.EnclosingClassNameNone != null){
            sb.append(this.EnclosingClassNameNone.apply(i, "", nb_macros));
        }
    
        for(Macro macro : macros){
            expansion = macro.build(local_context);
    
            if(this.EnclosingClassNameBeforeFirst != null){
                expansion = this.EnclosingClassNameBeforeFirst.apply(i, expansion, nb_macros);
            }
    
            if(this.EnclosingClassNameAfterLast != null){
                expansion = this.EnclosingClassNameAfterLast.apply(i, expansion, nb_macros);
            }
    
            if(this.EnclosingClassNameSeparator != null){
                expansion = this.EnclosingClassNameSeparator.apply(i, expansion, nb_macros);
            }
    
            sb.append(expansion);
            i++;
        }
    
        return sb.toString();
    }
    
    String buildIndexBuilder(){
    
        return this.field_IndexBuilder;
    }
    
    String buildIndexInsert(){
    
        return this.field_IndexInsert;
    }
    
    private String buildMacroBodyParts(){
        StringBuilder sb = new StringBuilder();
        Context local_context = MacroBodyPartsContext;
        List<Macro> macros = this.list_MacroBodyParts;
    
        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;
    
        if(this.MacroBodyPartsNone != null){
            sb.append(this.MacroBodyPartsNone.apply(i, "", nb_macros));
        }
    
        for(Macro macro : macros){
            expansion = macro.build(local_context);
    
            if(this.MacroBodyPartsBeforeFirst != null){
                expansion = this.MacroBodyPartsBeforeFirst.apply(i, expansion, nb_macros);
            }
    
            if(this.MacroBodyPartsAfterLast != null){
                expansion = this.MacroBodyPartsAfterLast.apply(i, expansion, nb_macros);
            }
    
            if(this.MacroBodyPartsSeparator != null){
                expansion = this.MacroBodyPartsSeparator.apply(i, expansion, nb_macros);
            }
    
            sb.append(expansion);
            i++;
        }
    
        return sb.toString();
    }
    
    private String buildSetInternals(){
        StringBuilder sb = new StringBuilder();
        Context local_context = SetInternalsContext;
        List<Macro> macros = this.list_SetInternals;
    
        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;
    
        if(this.SetInternalsNone != null){
            sb.append(this.SetInternalsNone.apply(i, "", nb_macros));
        }
    
        for(Macro macro : macros){
            expansion = macro.build(local_context);
    
            if(this.SetInternalsBeforeFirst != null){
                expansion = this.SetInternalsBeforeFirst.apply(i, expansion, nb_macros);
            }
    
            if(this.SetInternalsAfterLast != null){
                expansion = this.SetInternalsAfterLast.apply(i, expansion, nb_macros);
            }
    
            if(this.SetInternalsSeparator != null){
                expansion = this.SetInternalsSeparator.apply(i, expansion, nb_macros);
            }
    
            sb.append(expansion);
            i++;
        }
    
        return sb.toString();
    }
    
    private String buildSingleElementLists(){
        StringBuilder sb = new StringBuilder();
        Context local_context = SingleElementListsContext;
        List<Macro> macros = this.list_SingleElementLists;
    
        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;
    
        if(this.SingleElementListsNone != null){
            sb.append(this.SingleElementListsNone.apply(i, "", nb_macros));
        }
    
        for(Macro macro : macros){
            expansion = macro.build(local_context);
    
            if(this.SingleElementListsBeforeFirst != null){
                expansion = this.SingleElementListsBeforeFirst.apply(i, expansion, nb_macros);
            }
    
            if(this.SingleElementListsAfterLast != null){
                expansion = this.SingleElementListsAfterLast.apply(i, expansion, nb_macros);
            }
    
            if(this.SingleElementListsSeparator != null){
                expansion = this.SingleElementListsSeparator.apply(i, expansion, nb_macros);
            }
    
            sb.append(expansion);
            i++;
        }
    
        return sb.toString();
    }
    
    String getReferencedMacroName(){
    
        return this.field_ReferencedMacroName;
    }
    
    private InternalValue getEnclosingClassName(){
        return this.EnclosingClassNameValue;
    }
    
    String getIndexBuilder(){
    
        return this.field_IndexBuilder;
    }
    
    String getIndexInsert(){
    
        return this.field_IndexInsert;
    }
    
    private InternalValue getMacroBodyParts(){
        return this.MacroBodyPartsValue;
    }
    
    private InternalValue getSetInternals(){
        return this.SetInternalsValue;
    }
    
    private InternalValue getSingleElementLists(){
        return this.SingleElementListsValue;
    }
    private void initEnclosingClassNameInternals(Context context){
        for(Macro macro : this.list_EnclosingClassName){
            macro.apply(new InternalsInitializer("EnclosingClassName"){
                @Override
                void setPlainText(MPlainText mPlainText){
                
                    
                    
                }
            });
        }
    }
    
    private void initMacroBodyPartsInternals(Context context){
        for(Macro macro : this.list_MacroBodyParts){
            macro.apply(new InternalsInitializer("MacroBodyParts"){
                @Override
                void setInitStringBuilder(MInitStringBuilder mInitStringBuilder){
                
                    
                    
                }
                
                @Override
                void setStringPart(MStringPart mStringPart){
                
                    
                    
                }
                
                @Override
                void setParamInsertPart(MParamInsertPart mParamInsertPart){
                
                    
                    
                }
                
                @Override
                void setEolPart(MEolPart mEolPart){
                
                    
                    
                }
                
                @Override
                void setInsertMacroPart(MInsertMacroPart mInsertMacroPart){
                
                    
                    
                }
            });
        }
    }
    
    private void initSetInternalsInternals(Context context){
        for(Macro macro : this.list_SetInternals){
            macro.apply(new InternalsInitializer("SetInternals"){
                @Override
                void setSetInternal(MSetInternal mSetInternal){
                
                    
                    mSetInternal.setVarName(SetInternalsContext, getIndexInsert());
                }
            });
        }
    }
    
    private void initSingleElementListsInternals(Context context){
        for(Macro macro : this.list_SingleElementLists){
            macro.apply(new InternalsInitializer("SingleElementLists"){
                @Override
                void setNewStringValue(MNewStringValue mNewStringValue){
                
                    
                    
                }
            });
        }
    }
    
    private void initEnclosingClassNameDirectives(){
        StringBuilder sb1 = new StringBuilder();
        sb1.append(".");
        this.EnclosingClassNameAfterLast = new DAfterLast(sb1.toString());
        this.EnclosingClassNameValue.setAfterLast(this.EnclosingClassNameAfterLast);StringBuilder sb2 = new StringBuilder();
        sb2.append("M");
        this.EnclosingClassNameBeforeFirst = new DBeforeFirst(sb2.toString());
        this.EnclosingClassNameValue.setBeforeFirst(this.EnclosingClassNameBeforeFirst);
    }
    
    private void initMacroBodyPartsDirectives(){
        StringBuilder sb1 = new StringBuilder();
        sb1.append(LINE_SEPARATOR);
        this.MacroBodyPartsSeparator = new DSeparator(sb1.toString());
        this.MacroBodyPartsValue.setSeparator(this.MacroBodyPartsSeparator);
    }
    
    private void initSetInternalsDirectives(){
        StringBuilder sb1 = new StringBuilder();
        sb1.append(LINE_SEPARATOR);
        this.SetInternalsSeparator = new DSeparator(sb1.toString());
        this.SetInternalsValue.setSeparator(this.SetInternalsSeparator);
    }
    
    private void initSingleElementListsDirectives(){
        StringBuilder sb1 = new StringBuilder();
        sb1.append(LINE_SEPARATOR);
        this.SingleElementListsSeparator = new DSeparator(sb1.toString());
        this.SingleElementListsValue.setSeparator(this.SingleElementListsSeparator);
    }
    @Override
    void apply(
            InternalsInitializer internalsInitializer){
    
        internalsInitializer.setInsertMacroPart(this);
    }
    
    
    public String build(){
    
        CacheBuilder cache_builder = this.cacheBuilder;
    
        if(cache_builder == null){
            cache_builder = new CacheBuilder();
        }
        else if(cache_builder.getExpansion() == null){
            throw new InternalException("Cycle detection detected lately");
        }
        else{
            return cache_builder.getExpansion();
        }
        this.cacheBuilder = cache_builder;
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        initEnclosingClassNameDirectives();
        initMacroBodyPartsDirectives();
        initSetInternalsDirectives();
        initSingleElementListsDirectives();
        
        initEnclosingClassNameInternals(null);
        initMacroBodyPartsInternals(null);
        initSetInternalsInternals(null);
        initSingleElementListsInternals(null);
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append("M");
        sb0.append(buildReferencedMacroName());
        sb0.append(" m");
        sb0.append(buildIndexInsert());
        sb0.append(" = ");
        sb0.append(buildEnclosingClassName());
        sb0.append("this.getMacros().new");
        sb0.append(buildReferencedMacroName());
        sb0.append("();");
        sb0.append(LINE_SEPARATOR);
        sb0.append(buildMacroBodyParts());
        sb0.append(LINE_SEPARATOR);
        sb0.append(buildSingleElementLists());
        sb0.append(LINE_SEPARATOR);
        sb0.append(buildSetInternals());
        sb0.append(LINE_SEPARATOR);
        sb0.append("sb");
        sb0.append(buildIndexBuilder());
        sb0.append(".append(m");
        sb0.append(buildIndexInsert());
        sb0.append(".build(null));");
    
        cache_builder.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    @Override
    String build(Context context) {
        return build();
    }
    
    
    private void setMacros(Macros macros){
        if(macros == null){
            throw new InternalException("macros cannot be null");
        }
    
        this.macros = macros;
    }
}