/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public  class MStringValueArg extends Macro{
    
    String field_Index;
    
    MStringValueArg(String pIndex, Macros macros){
        
        
        this.setMacros(macros);
        this.setPIndex(pIndex);
    }
    
    private void setPIndex( String pIndex ){
        if(pIndex == null){
            throw ObjectMacroException.parameterNull("Index");
        }
    
        this.field_Index = pIndex;
    }
    
    String buildIndex(){
    
        return this.field_Index;
    }
    
    String getIndex(){
    
        return this.field_Index;
    }
    
    
    @Override
    void apply(
            InternalsInitializer internalsInitializer){
    
        internalsInitializer.setStringValueArg(this);
    }
    
    
    public String build(){
    
        CacheBuilder cache_builder = this.cacheBuilder;
    
        if(cache_builder == null){
            cache_builder = new CacheBuilder();
        }
        else if(cache_builder.getExpansion() == null){
            throw new InternalException("Cycle detection detected lately");
        }
        else{
            return cache_builder.getExpansion();
        }
        this.cacheBuilder = cache_builder;
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        
    
    
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append("value");
        sb0.append(buildIndex());
    
        cache_builder.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    @Override
    String build(Context context) {
        return build();
    }
    
    
    private void setMacros(Macros macros){
        if(macros == null){
            throw new InternalException("macros cannot be null");
        }
    
        this.macros = macros;
    }
}